name: macOS
on: [push]
env:
  ERROR_ON_FAILURES: 1
jobs:
  clang:
    runs-on: macos-10.15
    strategy:
      matrix:
        symbols:
          - 'no'
          - 'mem'
        options:
          - '--disable-aqua'
    defaults:
      run:
        shell: bash
        working-directory: unix
    steps:
      - name: Check out Tk
        uses: actions/checkout@v2
      - name: Prepare checked out repository
        run: |
          touch ../generic/tkStubInit.c ../doc/man.macros
          mkdir "$HOME/install"
      - name: Add Tcl
        run: |
          brew install tcl-tk
      - name: Add X11
        run: |
          brew install --cask xquartz
          sudo /opt/X11/libexec/privileged_startx || true
      - name: Configure (symbols=${{ matrix.symbols }} ${{matrix.options }})
        # Note that macOS is always a 64 bit platform
        run: |
          ./configure --enable-64bit --enable-framework --with-tcl=/usr/local/opt/tcl-tk/lib --x-includes=/opt/X11/include --x-libraries=/opt/X11/lib CFLAGS=-I/usr/local/opt/tcl-tk/include ${CFGOPT} "--prefix=$HOME/install" || {
            cat config.log
            echo "::error::Failure during Configure"
            exit 1
          }
        env:
          CFGOPT: --enable-symbols=${{ matrix.symbols }} ${{matrix.options }}
      - name: Build
        run: |
          make binaries libraries tktest || {
            echo "::error::Failure during Build"
            exit 1
          }
      - name: Run Tests
        run: |
          function runXvfb {
            PATH=$PATH:/opt/X11/bin
            Xvfb $1 &
            XVFB_PID=$!
            echo Launched Xvfb $1 as process $XVFB_PID >&2
            trap "echo killing process $XVFB_PID... >&2; kill $XVFB_PID" 0
            export DISPLAY=$1
            sleep 2
          }
          ( runXvfb :0; make test-classic; exit $? ) | tee out-classic.txt || {
            echo "::error::Failure during Test (classic)"
            exit 1
          }
          ( runXvfb :0; make test-ttk; exit $? ) | tee out-ttk.txt || {
            echo "::error::Failure during Test (ttk)"
            exit 1
          }
          cat out-classic.txt | grep -q "Failed	0" || {
            echo "::error::Failure in classic test results"
            exit 1
          }
          cat out-ttk.txt | grep -q "Failed	0" || {
            echo "::error::Failure in ttk test results"
            exit 1
          }
        env:
          MAC_CI: 1
