name: macOS
on: [push]
env:
  ERROR_ON_FAILURES: 1
jobs:
  clang:
    runs-on: macos-10.15
    strategy:
      matrix:
        symbols:
          - 'no'
          - 'mem'
        options:
          - '--disable-aqua'
    defaults:
      run:
        shell: bash
        working-directory: unix
    steps:
      - name: Check out Tk
        uses: actions/checkout@v2
      - name: Prepare checked out repository
        run: |
          touch ../generic/tkStubInit.c ../doc/man.macros
          mkdir "$HOME/install"
          echo "USE_XVFB=$USE_XVFB" >> $GITHUB_ENV
        env:
          USE_XVFB: ${{ contains(matrix.options, '--disable-aqua') }}
      - name: Add Tcl
        run: |
          brew install tcl-tk
      - name: Add X11
        if: ${{ env.USE_XVFB }}
        # This involves black magic
        run: |
          brew install --cask xquartz
          sudo /opt/X11/libexec/privileged_startx || true
      - name: Configure (symbols=${{ matrix.symbols }} ${{matrix.options }})
        # Note that macOS is always a 64 bit platform
        run: |
          ./configure --enable-64bit --enable-framework --with-tcl=/usr/local/opt/tcl-tk/lib --x-includes=/opt/X11/include --x-libraries=/opt/X11/lib CFLAGS=-I/usr/local/opt/tcl-tk/include ${CFGOPT} "--prefix=$HOME/install" || {
            cat config.log
            echo "::error::Failure during Configure"
            exit 1
          }
        env:
          CFGOPT: --enable-symbols=${{ matrix.symbols }} ${{matrix.options }}
      - name: Build
        run: |
          make binaries libraries tktest || {
            echo "::error::Failure during Build"
            exit 1
          }
      - name: Run Tests
        run: |
          if [ $USE_XVFB == true ]; then
            function runXvfb {
              PATH=$PATH:/opt/X11/bin
              Xvfb $1 &
              XVFB_PID=$!
              echo Launched Xvfb $1 as process $XVFB_PID >&2
              export DISPLAY=$1
              sleep 2
            }
          else
            function runXvfb {
              : do nothing
            }
          fi
          ( runXvfb :0; make test-classic test-ttk; exit $? ) | tee out.txt || {
            echo "::error::Failure during Test"
            exit 1
          }
          cat out.txt | grep -q "Failed	[1-9]" && {
            echo "::error::Failure in test results"
            exit 1
          }
        env:
          MAC_CI: 1
      - name: Carry out trial installation
        run: |
          sudo make install || {
            cat config.log
            echo "::error::Failure during Install"
            exit 1
          }
